@URL = http://127.0.0.1:5001

### ping
GET {{URL}}/ping HTTP/1.1

### search token
POST {{URL}} HTTP/1.1
Content-Type: application/json

{
    "method": "searchCoin",
    "args": {
        "network": "ethereum",
        "string": "USDC",
        "fromBitquery": true,
        "limit": 10,
        "offset": 273
    }
}

### search pair

POST {{URL}} HTTP/1.1
Content-Type: application/json

{
    "method": "searchPairs",
    "args": {
        "network": "ethereum",
        "currency": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
        "limit": 10,
        "offset": 0,
        "fromBitquery": false
    }
}